-- All dummy data currently in the Passenger Resource Management database.
-- Generated by Claude Code on 2026-08-06 04:44.
-- Includes seeded data (sampledata.sql + passengerresourceusage_sample.sql) plus
-- everything created during live testing (soft-deleted records and their audit trail).
-- Rows are ordered parent-before-child so this file can be replayed against a freshly
-- migrated (empty) database without foreign-key errors.

-- CrewLead (3 rows)
INSERT INTO CrewLead (CrewLeadID, CrewLeadAccessCode, CrewLeadEmployeeID, CrewLeadName) VALUES (1, '$2b$10$goAcQrFfWXcOvtd1ameyfeNZl6wLDBq5pkJ1/p1Vsjwzbp0lgdXPW', 'EMP001', 'Alice Smith');
INSERT INTO CrewLead (CrewLeadID, CrewLeadAccessCode, CrewLeadEmployeeID, CrewLeadName) VALUES (2, '$2b$10$kuW/LfM528U5aob/LyIzAuMdheTYpSSvC5rY79iUzuWMqJDEtkbIm', 'EMP002', 'Ben Reyes');
INSERT INTO CrewLead (CrewLeadID, CrewLeadAccessCode, CrewLeadEmployeeID, CrewLeadName) VALUES (3, '$2b$10$unB2QUZeRbUOAF.C3pJyquD09iWDbyfmI64L1HHZpDUV7QrCOanIC', 'EMP003', 'Chloe Patel');

-- PassengerTier (4 rows)
INSERT INTO PassengerTier (PassengerTierID, PassengerTierName, IsDeleted) VALUES (1, 'Silver', 0);
INSERT INTO PassengerTier (PassengerTierID, PassengerTierName, IsDeleted) VALUES (2, 'Gold', 0);
INSERT INTO PassengerTier (PassengerTierID, PassengerTierName, IsDeleted) VALUES (3, 'Platinum', 0);
INSERT INTO PassengerTier (PassengerTierID, PassengerTierName, IsDeleted) VALUES (4, 'TestTier', 1);

-- Passenger (10 rows)
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (1, '$2b$10$Y3E/CpJVjzz8DBaHVCMFk.ugll1HQuinCklzgmif9L7bcz3HN1rIm', 'Albert Jones', 1, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (2, '$2b$10$eoJAjGYk6g.2f02avyTpCe.NWzYdSDuTOaNegixoUV3UMtS6BUE7S', 'Bernard Okafor', 1, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (3, '$2b$10$UTqAEa1p4NSqeLGLVrRyKusWg0Z1Ss4jsodWcCt8Rz3jmuhPD4zdi', 'Clark Thornton', 1, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (4, '$2b$10$M1Qny.yXVafHBlzyQbYQCucJjZcYbWguwVb4fCF1D0ZAFdcq3rmHa', 'Daniel Welsh', 1, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (5, '$2b$10$lUTSKXmUu11jJL1sCLKiVuizqluVDx8gpaOHAKH4vUWgOBAypI.cC', 'Elly Nguyen', 2, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (6, '$2b$10$Frw4cbkqD0yJjxzYTAN.DepJWt95JhfdjU4xNSLZYseDWtRID9pMe', 'Frank Yamada', 2, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (7, '$2b$10$DSvqeojYz9ufnmhyeIiFdO2btisHzQPxejBoXdjLCYT8L2Wj3CRVm', 'Gilbert Fernandez', 2, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (8, '$2b$10$3jNNewi0UH9DiXP6AjttBOwzo.Gtvrg4DAc/LgdQxW7cqGiDUfRA.', 'Helena Kim', 3, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (9, '$2b$10$mh.fe.uXA5J4ESDuBTwwpO7McGRvqEa3BHZKIZ/rmXa7BJWS5o/VC', 'Iona Osei', 3, 0);
INSERT INTO Passenger (PassengerID, PassengerAccessCode, PassengerName, PassengerTierID, IsDeleted) VALUES (10, '$2b$10$uSTjtR1F9aBTpLHgTqcciOtxBmGnIz/kUZcQ9L/HcYJ8pFYitL4ki', 'Zoe Test', 2, 1);

-- Resource (7 rows)
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (1, 'Food Stations', '[1,2,3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (2, 'Sleeping Pods', '[1,2,3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (3, 'Basic Hygiene', '[1,2,3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (4, 'Private Cabins', '[2,3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (5, 'Adv. Medical Bay', '[2,3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (6, 'Luxury O2 Pods', '[3]', 0);
INSERT INTO Resource (ResourceID, ResourceName, PassengerTierIDs, IsDeleted) VALUES (7, 'VIP Rec Deck', '[3]', 0);

-- PassengerResourceUsage (28 rows)
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (1, 1, 1, '2026-06-15 08:30:00', '2026-06-15 08:55:00', 1500, 'Passenger_001', 'Passenger_001');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (2, 2, 2, '2026-06-15 09:00:00', '2026-06-15 11:00:00', 7200, 'Passenger_002', 'Passenger_002');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (3, 3, 3, '2026-06-16 07:45:00', '2026-06-16 08:05:00', 1200, 'CrewLead_001', 'Passenger_003');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (4, 4, 1, '2026-06-16 12:00:00', '2026-06-16 12:30:00', 1800, 'Passenger_004', 'Passenger_004');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (5, 5, 4, '2026-06-17 14:00:00', '2026-06-17 15:00:00', 3600, 'Passenger_005', 'Passenger_005');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (6, 6, 5, '2026-06-17 10:30:00', '2026-06-17 11:15:00', 2700, 'CrewLead_002', 'CrewLead_002');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (7, 7, 1, '2026-06-18 08:00:00', '2026-06-18 08:35:00', 2100, 'Passenger_007', 'Passenger_007');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (8, 8, 6, '2026-06-18 15:00:00', '2026-06-18 16:00:00', 3600, 'Passenger_008', 'Passenger_008');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (9, 9, 7, '2026-06-19 11:00:00', '2026-06-19 12:30:00', 5400, 'CrewLead_003', 'CrewLead_003');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (10, 1, 2, '2026-06-20 22:00:00', '2026-06-21 02:00:00', 14400, 'CrewLead_001', 'Passenger_001');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (11, 5, 1, '2026-06-21 07:30:00', '2026-06-21 07:50:00', 1200, 'Passenger_005', 'Passenger_005');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (12, 8, 4, '2026-06-21 13:00:00', '2026-06-21 15:00:00', 7200, 'Passenger_008', 'Passenger_008');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (13, 6, 2, '2026-06-22 20:00:00', '2026-06-22 23:00:00', 10800, 'Passenger_006', 'Passenger_006');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (14, 9, 6, '2026-06-22 16:00:00', '2026-06-22 17:15:00', 4500, 'Passenger_009', 'CrewLead_001');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (15, 2, 3, '2026-06-23 06:00:00', '2026-06-23 06:15:00', 900, 'Passenger_002', 'Passenger_002');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (16, 3, 1, '2026-06-23 12:30:00', '2026-06-23 13:10:00', 2400, 'Passenger_003', 'Passenger_003');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (17, 7, 5, '2026-06-24 09:00:00', '2026-06-24 09:30:00', 1800, 'Passenger_007', 'Passenger_007');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (18, 8, 7, '2026-06-24 17:00:00', '2026-06-24 18:20:00', 4800, 'Passenger_008', 'Passenger_008');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (19, 4, 2, '2026-06-25 23:00:00', '2026-06-26 04:00:00', 18000, 'CrewLead_002', 'Passenger_004');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (20, 5, 4, '2026-06-26 10:00:00', '2026-06-26 11:30:00', 5400, 'Passenger_005', 'Passenger_005');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (21, 9, 7, '2026-06-27 14:00:00', '2026-06-27 16:00:00', 7200, 'Passenger_009', 'Passenger_009');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (22, 6, 1, '2026-06-28 08:00:00', '2026-06-28 08:25:00', 1500, 'Passenger_006', 'Passenger_006');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (23, 7, 4, '2026-06-28 15:00:00', '2026-06-28 16:00:00', 3600, 'CrewLead_003', 'CrewLead_003');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (24, 8, 5, '2026-06-29 11:00:00', '2026-06-29 11:45:00', 2700, 'Passenger_008', 'Passenger_008');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (25, 1, 3, '2026-06-30 07:00:00', '2026-06-30 07:12:00', 720, 'Passenger_001', 'Passenger_001');
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (26, 9, 1, '2026-07-01 09:00:00', NULL, NULL, 'Passenger_009', NULL);
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (27, 8, 6, '2026-07-01 10:30:00', NULL, NULL, 'CrewLead_002', NULL);
INSERT INTO PassengerResourceUsage (PassengerResourceUsageID, PassengerID, ResourceID, ResourceUsageStartDT, ResourceUsageEndDT, ResourceUsageTotalDuration, CreatedBy, UpdatedBy) VALUES (29, 5, 3, '2026-08-05 20:39:29', '2026-08-05 20:39:36', 7, 'CrewLead_001', 'CrewLead_001');

-- PassengerTierAudit (2 rows)
INSERT INTO PassengerTierAudit (PassengerTierAuditID, PassengerTierID, Action, Old_PassengerTierName, New_PassengerTierName, CreatedOn, CreatedBy) VALUES (1, 4, 'Create', NULL, 'TestTier', '2026-08-05 20:40:19', 'CrewLead_001');
INSERT INTO PassengerTierAudit (PassengerTierAuditID, PassengerTierID, Action, Old_PassengerTierName, New_PassengerTierName, CreatedOn, CreatedBy) VALUES (2, 4, 'Delete', 'TestTier', NULL, '2026-08-05 20:40:39', 'CrewLead_001');

-- PassengerAudit (2 rows)
INSERT INTO PassengerAudit (PassengerAuditID, PassengerID, Action, Old_PassengerName, New_PassengerName, Old_PassengerTierID, New_PassengerTierID, CreatedOn, CreatedBy) VALUES (1, 10, 'Create', NULL, 'Zoe Test', NULL, 2, '2026-08-05 20:41:48', 'CrewLead_001');
INSERT INTO PassengerAudit (PassengerAuditID, PassengerID, Action, Old_PassengerName, New_PassengerName, Old_PassengerTierID, New_PassengerTierID, CreatedOn, CreatedBy) VALUES (2, 10, 'Delete', 'Zoe Test', NULL, 2, NULL, '2026-08-05 20:41:59', 'CrewLead_001');

-- ResourceAudit (0 rows)
-- (no rows)
